now with official semantic versioning regex

diff --git a/.github/workflows/merge-version-publish.yml b/.github/workflows/merge-version-publish.yml
--- a/.github/workflows/merge-version-publish.yml
+++ b/.github/workflows/merge-version-publish.yml
@@ -38,13 +38,14 @@ jobs:
         run: |
           echo "Fetching GHCR versions..."
 
-          JSON=$(gh api -H "Accept: application/vnd.github+json" \
-                  /orgs/mut-ink/packages/container/mut-ink-test/versions 2>/dev/null || echo "")
-
+          JSON=$(
           gh api -H "Accept: application/vnd.github+json" \
-                  /orgs/mut-ink/packages/container/mut-ink-test/versions 
+                  /orgs/mut-ink/packages/container/mut-ink-test/versions | \
+          jq -r '.[] | .metadata.container.tags[] | select(test("^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\d*|\\d*[a-zA-Z-][a-zA-Z0-9-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][a-zA-Z0-9-]*))*))?(?:\\+([a-zA-Z0-9-]+(?:\\.[a-zA-Z0-9-]+)*))?$"))' 2>/dev/null || echo "")
+
 
           if [ -z "$JSON" ]; then
+            echo "Couldn't find any package versions"
             echo "LATEST=0.0.0" >> $GITHUB_OUTPUT
             exit 0
           fi
